version: 1

dataset_path: '.datasets/Conversa do WhatsApp com Barão Jovem.txt'
logs_path: '.logs'

database_path: '.db/wpp2_messages.db'
driver: 'sqlite:///'
table_name: 'messages'
chunk_size: 10000