SYSTEM_AUTHOR_NAME = "SYSTEM"

DEFAULT_TYPE = "COMMON_CONVERSATION"
MEMBER_LEFT_TYPE = "MEMBER_LEFT_NOTIFICATION"
MEMBER_ADDED_TYPE = "MEMBER_ADDED_NOTIFICATION"
MEMBER_ID_MAPPING_TYPE = "MEMBER_ID_MAPPING_NOTIFICATION"
OTHER_MSG_TYPE = "OTHER"

MESSAGE_TYPES = {
    DEFAULT_TYPE,
    MEMBER_ADDED_TYPE,
    MEMBER_ID_MAPPING_TYPE,
    MEMBER_LEFT_TYPE,
    OTHER_MSG_TYPE,
}
